name: Upload UI Tests Summary

description: |
  Uploads the UI tests summary reports to pull requests.

inputs:
  artifacts_path:
    description: 'The artifacts path for results file.'
    required: true
  pull_request_number:
    description: 'The artifacts path for results file.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install PyGithub
      run: pip install PyGithub
      shell: bash  
    
    - name: Publish Test Results
      env:
        ARTIFACT_PATH: ${{ inputs.artifacts_path }}
        ACCESS_TOKEN: $GITHUB_TOKEN
        PR_NUMBER: ${{ inputs.pull_request_number }}
        REPOSITORY: ${{ github.repository }}
      run: |
        pwd
        ls -R .
        echo 'ARTIFACT_PATH: ${{ inputs.artifacts_path }}' 
        echo 'ACCESS_TOKEN: ${{ github.token }}' 
        echo 'PR_NUMBER: ${{ inputs.pull_request_number }}' 
        echo 'REPOSITORY: ${{ github.repository }}' 
        
        chmod +x $GITHUB_ACTION_PATH/ui-tests-summary.py
        python $GITHUB_ACTION_PATH/ui-tests-summary.py
      shell: bash  
